### PR TITLE
New map style (Maptiler vector tiles)

### LINKED ISSUE #4: use a more similar map style
Maybe we could use https://www.maptiler.com/

### PR DESCRIPTION
**Pull request by hb0nd**
Also reduced the shadow, and fixed a spelling mistake.

Demo here: https://url-processor.endim8.workers.dev/otdd0UFQSp/Southwark+Underground+Station

New:
Screenshot from 2023-03-17 21-32-52

Screenshot from 2023-03-17 23-28-11

Old:
Screenshot from 2023-03-17 21-25-44

we have up to 100k API requests/month for free. 
currently uses my account api key for the free tier, the style is attatched if the account needs to be changed:
[OrganicMaps.zip](https://github.com/organicmaps/url-processor/files/11006963/OrganicMaps.zip)

fixes https://github.com/organicmaps/url-processor/issues/4

### CODE REVIEW

**Comment by hb0nd** [comment]
ptal @biodranik :)

**Comment by biodranik** [comment]
Thanks, but the 100K limit would be too low.

**Comment by hb0nd** [comment]
> Thanks, but the 100K limit would be too low.

damn :( how much do we need?

**Comment by hb0nd** [comment]
we could use this! https://protomaps.com/ statically served vector tiles

edit:
mm, it doesn't look practical for high zooms...

**Comment by biodranik** [comment]
An interesting task would be to render tiles by OM's C++ core )

Are there any other better free styles in OSM that are already available?

**Comment by biodranik** [comment]
Storing some static data as a temporary solution is also not a big issue if we can easily update it on changes. It would be great to render the style that is similar to the current OM one :)

**Pull request closed without merging**
