### PR TITLE
also query features at point in OSM link

### PR DESCRIPTION
**Pull request by hb0nd**
Also query features around the marker when viewing on OSM, for easier selection.

Before/after:

https://github.com/organicmaps/url-processor/assets/26939824/5583c3a8-a241-4b0e-b63b-4e0701696764

It's slightly hacky because it needs both mlon/mlat and lon/lat. and the #map section (with another lon/lat) is required to specify the zoom. but it does work!

### CODE REVIEW

**Comment by biodranik** [comment]
How does it work/look on mobile devices?

**Comment by hb0nd** [comment]
looks fine:

**Comment by biodranik** [comment]
Mmm... there's almost no visible map ) What's the goal?

**Comment by hb0nd** [comment]
> Mmm... there's almost no visible map ) What's the goal?

well, if you're opening a poi on the osm website, it's most likely that you want to check the tags, which is easier with this

**Review by biodranik — APPROVED** [review]
Ok, let's see how it flies. Thanks!

**Pull request merged**
